name: Build Custom Caddy for Debian 11

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.22-bullseye

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build Caddy with plugins
        run: |
          xcaddy build \
            --with github.com/mholt/caddy-l4 \
            --with github.com/klzgrad/forwardproxy \
            --with github.com/caddyserver/replace-response

      - name: Upload Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: caddy-amd64
          path: caddy
          retention-days: 35
